version: '2.4'

services:
  map_workers:
    build: .
    environment:
      - report_store_stage
    volumes:
      - $report_store_stage:/data/report
    command: >
      /bin/sh -c
      "cd /dj_map
      && python scripts/mapshell.py automate-computation
      & python scripts/mapshell.py automate-computation
      & python scripts/mapshell.py automate-computation
      & tail -f /dev/null"